{
  imports = [
    ./catppuccin.nix
    ./devshells
    ./direnv.nix
    ./helix.nix
    ./hypr.nix
    ./fastfetch.nix
    ./firefox.nix
    ./fuzzel.nix
    ./kitty.nix
    ./mako.nix
    ./music.nix
    ./nixvim.nix
    ./scripts.nix
    ./wallpaper.nix
    ./waybar.nix
    ./zsh.nix
  ];
}
