{
  imports = [
    ./devshells/default.nix
    ./direnv.nix
    ./helix.nix
    ./hypr.nix
    ./fastfetch.nix
    ./firefox.nix
    ./gtk.nix
    ./kitty.nix
    ./mako.nix
    ./mpv.nix
    ./music.nix
    ./nixvim.nix
    ./scripts.nix
    ./stylix.nix
    ./wallpaper.nix
    ./waybar/default.nix
    ./zsh.nix
  ];
}
